/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e1c57a84-d6c9-496b-916f-6aef9cd393c0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_pGBBYVeMC",
    "aws_user_pools_web_client_id": "1aik6500t5b3pk9lh9m5fm5rki",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fv2nxgep65eodepr5ffvvyivcy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "2306564b164d42afbeae2746c8ddf31f",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
